services:
  - type: web
    name: lms-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend-node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
